### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by naonxj** [Gigamakhijo/StunningApp2#7]
npm expo start --clear 후 문제 발생

npx run expo:ios 실행시 밑에 오류 발생
<img width="727" alt="스크린샷 2024-05-07 오후 1 03 33" src="https://github.com/Gigamakhijo/StunningApp2/assets/103016411/2d9e3a1f-8395-488f-abfa-e1295473505f">

해본 것중에 되는 것 
npx expo install
npx expo rebuild
npm install
안되는것
npx run install
npx react-native run-ins

**Comment by osj1405** [comment]
https://stackoverflow.com/questions/56744493/expo-cannot-find-module-after-reinstall
